### ISSUE TITLE
[NEED HELP] Building on Fedora 37 for local development fails

### ISSUE THREAD

**Issue by royrustdev** [BloopAI/bloop#223]
I'm running on Fedora 37 and trying to setup bloop for local development to begin contributions.

Packages I have installed:
```sh
# Got these from tauri docs
sudo dnf install webkit2gtk4.0-devel openssl-devel libappindicator-gtk3 librsvg2-devel
sudo dnf group install "C Development Tools and Libraries"

# other dev packages
sudo dnf install atk-devel dbus-devel glib-devel pango-devel gtk3-devel python3-devel snappy-devel lz4-devel

# This one solved openssl error
sudo dnf install perl-FindBin perl-File-Compare openssl-devel

sudo dnf install protobuf protobuf-devel protobuf-compiler
```

NOTE: No error/warning while running frontend
```sh
# running this from the project root directory
pnpm run start-web
```

I'm running qdrant in a container as well.
stdout of `docker ps`

```sh
b4da154dd537   qdrant/qdrant   "./qdrant"   2 hours ago   Up 2 hours   0.0.0.0:6333-6334->6333-6334/tcp, :::63
33-6334->6333-6334/tcp   friendly_snyder
```

COMMAND:
```sh
# running this command from project root
 pnpm run start-app
```

STDOUT:

```sh
> @bloop/root@ start-app /home/royrustdev/work/bloop
> npm --prefix apps/desktop run tauri-dev


> @bloop/desktop@0.0.0 tauri-dev
> npm-run-all build-qdrant "tauri dev"


> @bloop/desktop@0.0.0 build-qdrant
> ./build.sh

    Updating git repository `https://github.com/qdrant/qdrant`
  Installing qdrant v1.0.1 (https://github.com/qdrant/qdrant?tag=v1.0.1#486737d7)
    Updating crates.io index

# packages starts compiling

error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installtY6qgN/release/build/librocksdb-sys-ca99f743895cb957/build-script-build` (exit status: 101)
  --- stderr
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found
  thread 'main' panicked at 'unable to generate rocksdb bindings: ClangDiagnostic("rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found\n")', /home/royrustdev/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-0.8.0+7.4.4/build.rs:43:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `qdrant v1.0.1 (https://github.com/qdrant/qdrant?tag=v1.0.1#486737d7)`, intermediate artifacts can be found at `/tmp/cargo-installtY6qgN`
     Running BeforeDevCommand (`npm run dev`)
        Info Watching /home/royrustdev/work/bloop/server/bleep for changes...
        Info Watching /home/royrustdev/work/bloop/apps/desktop/src-tauri for changes...
   Compiling ort v1.13.2 (https://github.com/bloopai/ort?branch=build-rs-fix#1bd07b25)
   Compiling bloop v0.2.3 (/home/royrustdev/work/bloop/apps/desktop/src-tauri)
error: failed to run custom build command for `bloop v0.2.3 (/home/royrustdev/work/bloop/apps/desktop/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/royrustdev/work/bloop/target/debug/build/bloop-99c373d9b70321a7/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  cargo:rerun-if-changed=bin/ctags-x86_64-unknown-linux-gnu
  path matching bin/qdrant-x86_64-unknown-linux-gnu not found.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `ort v1.13.2 (https://github.com/bloopai/ort?branch=build-rs-fix#1bd07b25)`

Caused by:
  process didn't exit successfully: `/home/royrustdev/work/bloop/target/debug/build/ort-23af485ef9a0967b/build-script-build` (exit status: 101)
  --- stdout
  [ort] strategy: "unknown"
  cargo:rerun-if-env-changed=ORT_STRATEGY
  Python 3.11.2
  [ort] assuming C/C++ compilers are available

 path matching bin/qdrant-x86_64-unknown-linux-gnu not found.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `ort v1.13.2 (https://github.com/bloopai/ort?branch=build-rs-fix#1bd07b25)`

Caused by:
  process didn't exit successfully: `/home/royrustdev/work/bloop/target/debug/build/ort-23af485ef9a0967b/build-script-build` (exit status: 101)
  --- stdout
  [ort] strategy: "unknown"
  cargo:rerun-if-env-changed=ORT_STRATEGY
  Python 3.11.2
  [ort] assuming C/C++ compilers are available

  --- stderr
  2023-03-02 09:57:42,228 tools_python_utils [INFO] - flatbuffers module is not installed. parse_config will not be available
  2023-03-02 09:57:42,229 build [DEBUG] - Command line arguments:
    --build --update --parallel --skip_tests --skip_submodule_sync --config Release --disable_rtti --build_shared_lib --build_dir=build
  2023-03-02 09:57:42,232 build [INFO] - Build started
  2023-03-02 09:57:42,232 build [INFO] - Generating CMake build tree
  2023-03-02 09:57:42,232 util.run [INFO] - Running subprocess in 'build/Release'
    /usr/bin/cmake /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/cmake -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_GENERATE_TEST_REPORTS=ON -DPython_EXECUTABLE=/usr/bin/python3 -DPYTHON_EXECUTABLE=
  CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
    The OLD behavior for policy CMP0104 will be removed from a future version
    of CMake.

    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.


  Building ONNX Runtime for x86_64
  Patch found: /usr/bin/patch
  Use gtest from submodule
  Use nsync from submodule
  Use protobuf from submodule
  Use date from submodule
  Use mp11 from submodule
  Use json from submodule
  Use re2 from submodule
  Use cpuinfo from submodule
  NVCC_ERROR =
  NVCC_OUT = No such file or directory
  Generated: /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/build/Release/external/onnx/onnx/onnx-ml.proto
  Generated: /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/build/Release/external/onnx/onnx/onnx-operators-ml.proto
  Generated: /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/build/Release/external/onnx/onnx/onnx-data.proto
  Use flatbuffers from submodule
  fatal: No names found, cannot describe anything.
  CMake Warning (dev) at /usr/share/cmake/Modules/FetchContent.cmake:1282 (message):
    The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
    not set.  The policy's OLD behavior will be used.  When using a URL
    download, the timestamps of extracted files should preferably be that of
    the time of extraction, otherwise code that depends on the extracted
    contents might not be rebuilt if the URL changes.  The OLD behavior
    preserves the timestamps from the archive instead, but this is usually not
    what you want.  Update your project to the NEW behavior or specify the
    DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
    robustness issue.
  Call Stack (most recent call first):
    external/abseil-cpp.cmake:20 (FetchContent_Declare)
    onnxruntime_common.cmake:112 (include)
    CMakeLists.txt:2054 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.

 2023-03-02 09:57:42,978 util.run [DEBUG] - Subprocess completed. Return code: 0
  2023-03-02 09:57:42,978 build [INFO] - Building targets for Release configuration
  2023-03-02 09:57:42,979 util.run [INFO] - Running subprocess in '/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime'
    /usr/bin/cmake --build build/Release --config Release -- -j8
  In file included from /usr/lib/gcc/x86_64-redhat-linux/12/include/immintrin.h:49,
                   from /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h:44,
                   from /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/onnxruntime/core/mlas/lib/intrinsics/avx512/quantize_avx512f.cpp:21:

# THIS ERROR MESSAGE SHOWS IN A LOOP AND THEN STOP AFTER FEW ITERATION

 In function ‘__m512 _mm512_max_ps(__m512, __m512)’,
      inlined from ‘void MlasQuantizeLinearAvx512F(const float*, OutputType*, size_t, float, OutputType) [with OutputType = unsigned char]’ at /home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/onnxruntime/core/mlas/lib/intrinsics/avx512/quantize_avx512f.cpp:86:37:
  /usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:13033:10: error: ‘__Y’ may be used uninitialized [-Werror=maybe-uninitialized]
  13033 |   return (__m512) __builtin_ia32_maxps512_mask ((__v16sf) __A,
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  13034 |                                                 (__v16sf) __B,
        |                                                 ~~~~~~~~~~~~~~
  13035 |                                                 (__v16sf)
        |                                                 ~~~~~~~~~
  13036 |                                                 _mm512_undefined_ps (),
        |                                                 ~~~~~~~~~~~~~~~~~~~~~~~
  13037 |                                                 (__mmask16) -1,
        |                                                 ~~~~~~~~~~~~~~~
  13038 |                                                 _MM_FROUND_CUR_DIRECTION);
        |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h: In function ‘void MlasQuantizeLinearAvx512F(const float*, OutputType*, size_t, float, OutputType) [with OutputType = unsigned char]’:
  /usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:188:10: note: ‘__Y’ was declared here
    188 |   __m512 __Y = __Y;
        |          ^~~

# AFTER A FEW ITERATIONS THIS IS THE END MESSAGE

 cc1plus: all warnings being treated as errors
  gmake[2]: *** [CMakeFiles/onnxruntime_mlas.dir/build.make:885: CMakeFiles/onnxruntime_mlas.dir/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/onnxruntime/core/mlas/lib/intrinsics/avx512/quantize_avx512f.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:1833: CMakeFiles/onnxruntime_mlas.dir/all] Error 2
  gmake[1]: *** Waiting for unfinished jobs....
  gmake: *** [Makefile:166: all] Error 2
  Traceback (most recent call last):
    File "/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/tools/ci_build/build.py", line 2812, in <module>
      sys.exit(main())
               ^^^^^^
    File "/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/tools/ci_build/build.py", line 2727, in main
      build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
    File "/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/tools/ci_build/build.py", line 1349, in build_targets
      run_subprocess(cmd_args, env=env)
    File "/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/tools/ci_build/build.py", line 740, in run_subprocess
      return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/royrustdev/work/bloop/target/debug/build/ort-cf5dfe542e4bb86a/out/onnxruntime/tools/python/util/run.py", line 49, in run
      completed_process = subprocess.run(
                          ^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', 'build/Release', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.
  thread 'main' panicked at 'failed to build ONNX Runtime', /home/royrustdev/.cargo/git/checkouts/ort-c6432964096301e1/1bd07b2/build.rs:525:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR: "tauri dev" exited with 101.
```

If I remove the features flag `server/bleep/Cargo.toml`

```toml
ort = { git = "https://github.com/bloopai/ort", branch = "build-rs-fix" , features = ["prefer-compile-strategy", "compile-static"] }
```

to

```toml
ort = { git = "https://github.com/bloopai/ort", branch = "build-rs-fix" }
```

I get the following stdout

```sh
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installA3ukcF/release/build/librocksdb-sys-ca99f743895cb957/build-script-build` (exit status: 101)
  --- stderr
  rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found
  thread 'main' panicked at 'unable to generate rocksdb bindings: ClangDiagnostic("rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found\n")', /home/royrustdev/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-0.8.0+7.4.4/build.rs:43:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

ERROR: "tauri dev" exited with 101.
 ELIFECYCLE  Command failed with exit code 1.
```

NOTE: This time I don't receive those errors in loop.

This does not give any error and compiles fine.
```sh
cd server/bleep
cargo check
```

But if I run the server in one terminal by `cargo run` and run the frontend in another terminal with `pnpm run start-web`, the frontend running on `localhost:5173` does not work properly. After inspecting the page I see several `404` errors in browser console.

I need help with local installation. I want to contribute into the project. I might be missing some packages in my laptop that I'm not aware of. Kindly help me with this.

**Comment by nerdypepper** [comment]
>rocksdb/include/rocksdb/c.h:65:10: fatal error: 'stdarg.h' file not found

seems to indicate that you might be missing headers provided by libclang. while i am not entirely sure what package on fedora provides these headers, you could try installing `clang` or `libclang`.

>But if I run the server in one terminal by cargo run and run the frontend in another terminal with pnpm run start-web, the frontend running on localhost:5173 does not work properly. After inspecting the page I see several 404 errors in browser console.

you should be able to get it running with this patch: 
```diff
diff --git a/client/src/main.tsx b/client/src/main.tsx
index 2c60630..9617796 100644
--- a/client/src/main.tsx
+++ b/client/src/main.tsx
@@ -21,7 +21,7 @@ ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
         },
         invokeTauriCommand: () => {},
         release: packageJson.version,
-        apiUrl: import.meta.env.API_URL || '/api',
+        apiUrl: import.meta.env.API_URL || 'http://localhost:7878/api',
         isRepoManagementAllowed: true,
         isSelfServe: true,
         forceAnalytics: true,
```
